[package]
name = "quinn-min-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1.0" 
tokio = { version = "^1.19", features = ["full"] }
quinn = "0.9.3"
rustls = "^0.20"
rustls-pemfile = "^1.0"
futures-util = "^0.3"
rcgen = "0.10.0"